# Generated by Django 3.2.9 on 2021-12-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название доски')),
                ('slug', models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Доски',
                'verbose_name_plural': 'Доски',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Колонки')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.boards', verbose_name='Название доски')),
            ],
            options={
                'verbose_name': 'Колонки',
                'verbose_name_plural': 'Колонки',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название карточки')),
                ('content', models.TextField(verbose_name='Контент')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.boards', verbose_name='Название доски')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.column', verbose_name='Название колонки')),
            ],
            options={
                'verbose_name': 'Карточки',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
