# Generated by Django 3.2.9 on 2021-12-19 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название доски')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец доски')),
            ],
            options={
                'verbose_name': 'Доски',
                'verbose_name_plural': 'Доски',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Колонки')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.board', verbose_name='В какой доске')),
            ],
            options={
                'verbose_name': 'Колонки',
                'verbose_name_plural': 'Колонки',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название карточки')),
                ('content', models.TextField(verbose_name='Контент')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.column', verbose_name='В какой колонке')),
            ],
            options={
                'verbose_name': 'Карточки',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
