# Generated by Django 3.2.9 on 2021-12-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='board_id',
        ),
        migrations.AddField(
            model_name='card',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.boards'),
        ),
        migrations.AddField(
            model_name='column',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.boards'),
        ),
    ]
