# Generated by Django 3.2.9 on 2021-12-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211210_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'verbose_name': 'Доски', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточки', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'verbose_name': 'Колонки', 'verbose_name_plural': 'Колонки'},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='column_id',
            new_name='column',
        ),
    ]
