# Generated by Django 4.0 on 2022-01-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_card_column_alter_card_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='column',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.column', verbose_name='В какой колонке'),
        ),
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
